[package]
name = "rini"
version = "0.1.0"
authors = ["rini <rini@rinici.de>"]
edition = "2021"
description = "certified silly"
homepage = "https://rinici.de"
license = "Apache-2.0"

[dependencies]
maud = "0.26.0"

[[bin]]
name = "pages"
path = "pages/main.rs"
